"""Translate the analytic Kerr/q formulas from the maintained OpenCL source.

The browser integrator uses JavaScript float64. Only scalar metric routines
are translated; their mathematical expressions are kept verbatim. Run this
after editing those expressions in python/grayt/gpu/kernel.cl.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate():
    source = (ROOT / "python/grayt/gpu/kernel.cl").read_text()
    q = source.split("#if GRAYT_MID == 2", 1)[1].split("#else /* GRAYT_MID", 1)[0]
    kerr = source.split("#else /* GRAYT_MID == 1:", 1)[1].split(
        "#endif /* GRAYT_MID", 1
    )[0]
    kerr = kerr[kerr.index("static void") :]
    chunks = []
    for name, code in [("q", q), ("kerr", kerr)]:
        code = re.sub(
            r"static void (metric_\w+)\((.*?)\)",
            lambda m, name=name: (
                "function "
                + m[1].replace("metric", name)
                + "("
                + re.sub(r"\breal\s*\*?\s*", "", m[2])
                + ")"
            ),
            code,
            flags=re.DOTALL,
        )
        code = code.replace("(real)", "").replace("real ", "let ")
        chunks.append(code.strip())
    return (
        """// Generated by examples/build_browser_metrics.py; edit kernel.cl instead.
// Float64 evaluation of the same analytic metric and derivatives.
globalThis.GraytMetrics = (() => {
const {sin, cos, exp, log} = Math;
const fmax = Math.max, QM_FLOOR = 1e-14;
"""
        + "\n\n".join(chunks)
        + "\nreturn {kerr_cov, kerr_contra, q_cov, q_contra};\n})();\n"
    )


if __name__ == "__main__":
    (ROOT / "python/grayt/web/metrics.js").write_text(generate())
