spacetime: {type: kerr, a: 0.8}
camera:
  r: 100
  theta: 70
  phi: 0
  x: [-26, 26]
  y: [-16, 16]
  resolution: [640, 400]
disk: {model: page-thorne-bolometric, r_out: 20}
sky: {type: nasa}
exposure: 5000
escape_radius: 200
integrator: {method: rkdp45, rtol: 2.0e-9, atol: 2.0e-11}
