MODULE KIND_PARAMS
   ! Working precision and mathematical constants.
   USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
   IMPLICIT NONE
   PRIVATE

   INTEGER, PARAMETER, PUBLIC :: WP = REAL64
   REAL(WP), PARAMETER, PUBLIC :: PI = 3.14159265358979323846_WP
   REAL(WP), PARAMETER, PUBLIC :: HALF_PI = 0.5_WP*PI

END MODULE KIND_PARAMS
