// Generated by examples/build_browser_metrics.py; edit kernel.cl instead.
// Float64 evaluation of the same analytic metric and derivatives.
globalThis.GraytMetrics = (() => {
const {sin, cos, exp, log} = Math;
const fmax = Math.max, QM_FLOOR = 1e-14;
/* q-metric (Zipoy-Voorhees), src/q_metric.f90; par = quadrupole q.
 * Fractional powers via shared logs (2 log + 2 exp instead of 4 pow). */
function q_cov(q, r, theta, gd)
{
    let s2 = sin(theta); s2 *= s2;
    let f = fmax((1.0 - 2.0/r), QM_FLOOR);
    let h = fmax((1.0 + s2/(r*r - 2.0*r)), QM_FLOOR);
    let alpha = q*(2.0 + q);
    let fq = exp(q*log(f));
    let f1q = f*fq;
    let ha = exp(alpha*log(h));
    gd[0] = -f1q;
    gd[1] = 0.0;
    gd[2] = 1.0/(f1q*ha);
    gd[3] = r*r/(fq*ha);
    gd[4] = r*r*s2/fq;
}

function q_contra(q, r, theta,
                          gu, dgr, dgt)
{
    let s = sin(theta), c = cos(theta);
    let s2 = s*s;
    let u = r*r - 2.0*r;
    let f = fmax((1.0 - 2.0/r), QM_FLOOR);
    let h = fmax((1.0 + s2/u), QM_FLOOR);
    let alpha = q*(2.0 + q);

    /* logarithmic derivatives f'/f, h_r/h, h_th/h */
    let flr = (2.0/(r*r))/f;
    let hlr = (-s2*(2.0*r - 2.0)/(u*u))/h;
    let hlt = (2.0*s*c/u)/h;

    let fq = exp(q*log(f));
    let f1q = f*fq;
    let ha = exp(alpha*log(h));

    gu[0] = -1.0/f1q;
    dgr[0] = gu[0]*(-(1.0 + q)*flr);
    dgt[0] = 0.0;

    gu[1] = 0.0; dgr[1] = 0.0; dgt[1] = 0.0;

    gu[2] = f1q*ha;
    dgr[2] = gu[2]*((1.0 + q)*flr + alpha*hlr);
    dgt[2] = gu[2]*(alpha*hlt);

    gu[3] = fq*ha/(r*r);
    dgr[3] = gu[3]*(q*flr + alpha*hlr - 2.0/r);
    dgt[3] = gu[3]*(alpha*hlt);

    gu[4] = fq/(r*r*s2);
    dgr[4] = gu[4]*(q*flr - 2.0/r);
    dgt[4] = gu[4]*(-2.0*c/s);
}

function kerr_cov(a, r, theta, gd)
{
    let s2 = sin(theta); s2 *= s2;
    let ct = cos(theta);
    let sigma = r*r + a*a*ct*ct;
    let delta = r*r - 2.0*r + a*a;
    gd[0] = -(1.0 - 2.0*r/sigma);
    gd[1] = -2.0*a*r*s2/sigma;
    gd[2] = sigma/delta;
    gd[3] = sigma;
    gd[4] = s2*(r*r + a*a + 2.0*a*a*r*s2/sigma);
}

function kerr_contra(a, r, theta,
                          gu, dgr, dgt)
{
    let s = sin(theta), c = cos(theta);
    let s2 = s*s;
    let sin2t = 2.0*s*c;

    let sigma = r*r + a*a*c*c;
    let delta = r*r - 2.0*r + a*a;
    let af = (r*r + a*a)*(r*r + a*a) - a*a*delta*s2;

    let dsig_r = 2.0*r;
    let dsig_th = -a*a*sin2t;
    let ddel_r = 2.0*r - 2.0;
    let daf_r = 4.0*r*(r*r + a*a) - a*a*s2*ddel_r;
    let daf_th = -a*a*delta*sin2t;

    let d = sigma*delta;
    let dd_r = dsig_r*delta + sigma*ddel_r;
    let dd_th = dsig_th*delta;
    let inv_d2 = 1.0/(d*d);
    let inv_s2g = 1.0/(sigma*sigma);

    gu[0] = -af/d;
    dgr[0] = -(daf_r*d - af*dd_r)*inv_d2;
    dgt[0] = -(daf_th*d - af*dd_th)*inv_d2;

    gu[1] = -2.0*a*r/d;
    dgr[1] = -2.0*a*(d - r*dd_r)*inv_d2;
    dgt[1] = 2.0*a*r*dd_th*inv_d2;

    gu[2] = delta/sigma;
    dgr[2] = (ddel_r*sigma - delta*dsig_r)*inv_s2g;
    dgt[2] = -delta*dsig_th*inv_s2g;

    gu[3] = 1.0/sigma;
    dgr[3] = -dsig_r*inv_s2g;
    dgt[3] = -dsig_th*inv_s2g;

    let n = delta - a*a*s2;
    let w = d*s2;
    let dn_r = ddel_r;
    let dn_th = -a*a*sin2t;
    let dw_r = dd_r*s2;
    let dw_th = dd_th*s2 + d*sin2t;
    let inv_w2 = 1.0/(w*w);
    gu[4] = n/w;
    dgr[4] = (dn_r*w - n*dw_r)*inv_w2;
    dgt[4] = (dn_th*w - n*dw_th)*inv_w2;
}
return {kerr_cov, kerr_contra, q_cov, q_contra};
})();
